### ISSUE TITLE
a error is thrown when create ts file

### ISSUE THREAD

**Issue by tjx666** [jeronimoek/color-picker-universal#121]
https://github.com/user-attachments/assets/f3052ed2-95b6-4592-afaf-e26d12aff10f

## error message

```node
log.ts:439   ERR s is not iterable: TypeError: s is not iterable
    at ot (/Users/yutengjing/.vscode/extensions/jeronimoekerdt.color-picker-universal-2.6.0/dist/main.js:3:3017)
    at Object.provideDocumentColors (/Users/yutengjing/.vscode/extensions/jeronimoekerdt.color-picker-universal-2.6.0/dist/main.js:3:7145)
    at se.provideColors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:127781)
```

## settings

```json
{
	"color-picker-universal.languages": [
        "javascript",
        "typescript",
        "javascriptreact",
        "typescriptreact"
    ],
    "color-picker-universal.ignoreVariableName": true,
}
```

## version

```
Color-picker-universal: v2.6.0
Version: 1.92.1 (Universal)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by jeronimoek** [comment]
Hi! This should be fixed in the latest release (v2.6.6)
I'll close this issue for now, let me know otherwise
